
    create table tb_contas (
       id_conta int8 generated by default as identity,
        instituicao_fin int4,
        nome_usuario varchar(255),
        saldo float8,
        senha varchar(255),
        tipo_conta int4,
        primary key (id_conta)
    );

    create table tb_despesas (
       id_despesas int8 generated by default as identity,
        data_pag_esperado timestamp,
        data_pagamento timestamp,
        tipo_despesa int4,
        valor float8,
        conta_id int8,
        primary key (id_despesas)
    );

    create table tb_receitas (
       id_receita int8 generated by default as identity,
        data_rec_esperado timestamp,
        data_recebimento timestamp,
        descricao varchar(255),
        tipo_receita int4,
        valor float8,
        conta_id int8,
        primary key (id_receita)
    );

    alter table if exists tb_despesas 
       add constraint FK8qc4rw4tp14fwd5ab90gjgu0u 
       foreign key (conta_id) 
       references tb_contas;

    alter table if exists tb_receitas 
       add constraint FKoxllf7a9rqpdsvrxc8t0ngtmt 
       foreign key (conta_id) 
       references tb_contas;